# TRS-15 Dependabot Configuration
# Emperor Daniel's Authorized Security & Dependency Management
# Built for TRS Alliance - Truth, Respect, System

version: 2
updates:
  # 🔥 NODE.JS / NPM PACKAGES
  - package-ecosystem: "npm"
    directory: "/" 
    schedule:
      interval: "weekly"
      day: "monday"
      time: "09:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 5
    reviewers:
      - "emperor-daniel"
      - "trs-brothers"
    assignees:
      - "emperor-daniel"
    labels:
      - "dependencies"
      - "trs-security"
      - "auto-update"
    allow:
      - dependency-type: "direct"
      - dependency-type: "indirect"
    ignore:
      # Ignore major version updates for critical packages
      - dependency-name: "firebase"
        update-types: ["version-update:semver-major"]
      - dependency-name: "react"
        update-types: ["version-update:semver-major"]

  # 🔥 GITHUB ACTIONS WORKFLOWS
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
      time: "10:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "emperor-daniel"
    assignees:
      - "emperor-daniel"
    labels:
      - "github-actions"
      - "trs-security"
      - "workflow-update"

  # 🔥 DOCKER CONTAINERS
  - package-ecosystem: "docker"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "wednesday"
      time: "11:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "emperor-daniel"
    labels:
      - "docker"
      - "trs-security"
      - "container-update"

  # 🔥 PYTHON PACKAGES (if using Python for AI integrations)
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "thursday"
      time: "12:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 3
    reviewers:
      - "emperor-daniel"
    labels:
      - "python"
      - "ai-dependencies"
      - "trs-security"
    allow:
      - dependency-type: "direct"

  # 🔥 TERRAFORM (Infrastructure as Code)
  - package-ecosystem: "terraform"
    directory: "/infrastructure"
    schedule:
      interval: "weekly"
      day: "friday"
      time: "13:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "emperor-daniel"
    labels:
      - "terraform"
      - "infrastructure"
      - "trs-security"

  # 🔥 COMPOSER (PHP if needed)
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "saturday"
      time: "14:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "emperor-daniel"
    labels:
      - "php"
      - "composer"
      - "trs-security"

  # 🔥 GRADLE (Java/Android if needed)
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "sunday"
      time: "15:00"
      timezone: "America/New_York"
    open-pull-requests-limit: 2
    reviewers:
      - "emperor-daniel"
    labels:
      - "java"
      - "gradle"
      - "trs-security"

# 🛡️ TRS SECURITY COMMIT MESSAGE TEMPLATE
# All Dependabot PRs will follow this pattern:
# "🔥 TRS-SECURITY: Bump [package] from [old-version] to [new-version]"
# 
# This ensures:
# ✅ Clear identification of security updates
# ✅ Consistent commit history for TRS audit trails
# ✅ Easy filtering for TRS Brother review processes
# ✅ Alignment with Emperor Daniel's truth standards

# 🚨 BROTHER REVIEW REQUIREMENTS:
# 1. All updates must be reviewed by Emperor Daniel or authorized TRS Brothers
# 2. Critical security updates get immediate Alpha Brother attention
# 3. Major version updates require manual approval
# 4. Firebase-related updates need extra scrutiny for TRS CLI compatibility
# 5. AI-related packages (DeepSeek, Dolphin integrations) need specialized review

# 🔥 TRS TRUTH STANDARDS:
# - No silent updates that could compromise operator systems
# - All changes documented in TRS Brother logs
# - Security-first approach to dependency management
# - Maintain compatibility with TRS-15 protocols
