name: Firebase Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout your repo
      - name: Checkout repo
        uses: actions/checkout@v4

      # 2. Setup Node.js environment (v18)
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      # 3. Install dependencies in functions folder
      - name: Install Functions dependencies
        run: npm install
        working-directory: ./functions

      # 4. Install Firebase CLI globally
      - name: Install Firebase CLI
        run: npm install -g firebase-tools

      # 5. Build your functions (adjust if you have a build script)
      - name: Build Functions
        run: npm run build
        working-directory: ./functions
        # Remove this step if no build step needed

      # 6. Deploy to Firebase Hosting and Functions
      - name: Deploy to Firebase
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        run: |
          firebase deploy --only hosting,functions --token "$FIREBASE_TOKEN"

